### ISSUE TITLE
Pillage du code d'AMAR sans citer les auteurs d'origine

### ISSUE THREAD

**Issue by Elrondo46** [liberodark/LCleaner#1]
Violation de la GPLV3 tu ne cites les auteurs d'origine du code inspiré, merci

**Comment by liberodark** [comment]
Désolé mais ce code ne sera pas conservé !

**Comment by liberodark** [comment]
En attendant je vous cite en tant que third party car le code est déjà pas mal modifié et le but et de ne plus l'utiliser à terme

**Comment by Elrondo46** [comment]
Du moment que c'est cité je n'ai rien à dire du tout.
A propos je vois le chan de l'autre, donc pour répondre à ton rire bête: "Je t'emmerde faut le savoir déjà", je ne discuterai pas plus avec toi.
